test:
  name: fabcar
  description: A simple fabcar workload simulation
  clients:
    type: local
    number: 3
  rounds:
  - label: generate
    txDuration: [60] # The test length in seconds
    rateControl:
    - type: linear-rate
      opts:
        startingTps: 10
        finishingTps: 200
    # the user callback module relative to the workspace
    arguments:
      clients: 3
      # Pattern is going to be evaluated as .*targetPattern.*
      targetPattern: ord1-hlf
      # Deploy Pumba after milliseconds:
      deployAfter: 10000
    callback: caliper/generate.js
observer:
  type: 'local'
  interval: 1
monitor:
  type: ['none']
  interval: 1