test:
  name: fabcar
  description: A simple fabcar workload simulation
  clients:
    type: local
    number: 3
  rounds:
  - label: generate
    txDuration: [60] # The test length in seconds
    rateControl:
    - type: linear-rate
      opts:
        startingTps: 10
        finishingTps: 100
    # the user callback module relative to the workspace
    arguments:
      clients: 3
      # Here comes PUMBA STUFF
      # kubectl commands in manager, use the awk magic!
    callback: caliper/generate.js
observer:
  type: 'local'
  interval: 1
monitor:
  type: ['none']
  interval: 1