 
name: "test-network"

#
# Schema version of the content. Used by the SDK to apply the corresponding parsing rules.
#
version: "1.0"

caliper:
  blockchain: fabric
  command:
    start: sleep 60s

info:
  Version: 1.4.3
  Size: 3 Orgs with 1 Peer
  Orderer: Solo
  Distribution: Kubernetes
  StateDB: CouchDB

clients:
  client0.org1.example.com:
    client:
      organization: Org1
      credentialStore:
        path: /tmp/hfc-kvs/org1
        cryptoStore:
          path: /tmp/hfc-cvs/org1
      clientPrivateKey:
        path: network/crypto-config/peerOrganizations/org1.svc.cluster.local/users/User1@org1.svc.cluster.local/msp/keystore/key.pem
      clientSignedCert:
        path: network/crypto-config/peerOrganizations/org1.svc.cluster.local/users/User1@org1.svc.cluster.local/msp/signcerts/User1@org1.svc.cluster.local-cert.pem

  client0.org2.example.com:
    client:
      organization: Org2
      credentialStore:
        path: /tmp/hfc-kvs/org2
        cryptoStore:
          path: /tmp/hfc-cvs/org2
      clientPrivateKey:
        path: network/crypto-config/peerOrganizations/org2.svc.cluster.local/users/User1@org2.svc.cluster.local/msp/keystore/key.pem
      clientSignedCert:
        path: network/crypto-config/peerOrganizations/org2.svc.cluster.local/users/User1@org2.svc.cluster.local/msp/signcerts/User1@org2.svc.cluster.local-cert.pem

  client0.org3.example.com:
    client:
      organization: Org3
      credentialStore:
        path: /tmp/hfc-kvs/org3
        cryptoStore:
          path: /tmp/hfc-cvs/org3
      clientPrivateKey:
        path: network/crypto-config/peerOrganizations/org3.svc.cluster.local/users/User1@org3.svc.cluster.local/msp/keystore/key.pem
      clientSignedCert:
        path: network/crypto-config/peerOrganizations/org3.svc.cluster.local/users/User1@org3.svc.cluster.local/msp/signcerts/User1@org3.svc.cluster.local-cert.pem

channels:
  # name of the channel
  mychannel:
    created: true
    orderers:
      - ord1-hlf-ord.orderers.svc.cluster.local

    # Required. list of peers from participating orgs
    peers:
      peer1-hlf-peer.org1.svc.cluster.local:
        eventSource: true
      peer2-hlf-peer.org2.svc.cluster.local:
        eventSource: true
      peer3-hlf-peer.org3.svc.cluster.local:
        eventSource: true

    chaincodes:
        - id: go
          version: v4
          language: golang
          path: chaincode/go

#
# list of participating organizations in this network
#
organizations:
  Org1:
    mspid: Org1MSP

    peers:
      - peer1-hlf-peer.org1.svc.cluster.local

    adminPrivateKey:
      path: network/crypto-config/peerOrganizations/org1.svc.cluster.local/users/Admin@org1.svc.cluster.local/msp/keystore/adminKey
    
    signedCert:
      path: network/crypto-config/peerOrganizations/org1.svc.cluster.local/users/Admin@org1.svc.cluster.local/msp/signcerts/Admin@org1.svc.cluster.local-cert.pem

  Org2:
    mspid: Org2MSP

    peers:
      - peer2-hlf-peer.org2.svc.cluster.local

    adminPrivateKey:
      path: network/crypto-config/peerOrganizations/org2.svc.cluster.local/users/Admin@org2.svc.cluster.local/msp/keystore/adminKey
    
    signedCert:
      path: network/crypto-config/peerOrganizations/org2.svc.cluster.local/users/Admin@org2.svc.cluster.local/msp/signcerts/Admin@org2.svc.cluster.local-cert.pem

  Org3:
    mspid: Org3MSP

    peers:
      - peer3-hlf-peer.org3.svc.cluster.local

    adminPrivateKey:
      path: network/crypto-config/peerOrganizations/org3.svc.cluster.local/users/Admin@org3.svc.cluster.local/msp/keystore/adminKey
    
    signedCert:
      path: network/crypto-config/peerOrganizations/org3.svc.cluster.local/users/Admin@org3.svc.cluster.local/msp/signcerts/Admin@org3.svc.cluster.local-cert.pem

orderers:
  ord1-hlf-ord.orderers.svc.cluster.local:
    url: grpc://ord1-hlf-ord.orderers.svc.cluster.local:7050
    grpcOptions:
      ssl-target-name-override: ord1-hlf-ord.orderers.svc.cluster.local

peers:
  peer1-hlf-peer.org1.svc.cluster.local:
    url: grpc://peer1-hlf-peer.org1.svc.cluster.local:7051
    grpcOptions:
      ssl-target-name-override: peer1-hlf-peer.org1.svc.cluster.local

  peer2-hlf-peer.org2.svc.cluster.local:
    url: grpc://peer2-hlf-peer.org2.svc.cluster.local:7051
    grpcOptions:
      ssl-target-name-override: peer2-hlf-peer.org2.svc.cluster.local

  peer3-hlf-peer.org3.svc.cluster.local:
    url: grpc://peer3-hlf-peer.org3.svc.cluster.local:7051
    grpcOptions:
      ssl-target-name-override: peer3-hlf-peer.org3.svc.cluster.local
