Application:
  Capabilities: &id001
    V1_1: false
    V1_2: false
    V1_3: true
  Policies: &id013
    Admins:
      Rule: MAJORITY Admins
      Type: ImplicitMeta
    Readers:
      Rule: ANY Readers
      Type: ImplicitMeta
    Writers:
      Rule: ANY Writers
      Type: ImplicitMeta
Capabilities:
  Application: *id001
  Channel: &id002
    V1_3: true
  Orderer: &id008
    V1_1: true
Channel:
  Capabilities: *id002
  Policies: &id012
    Admins:
      Rule: MAJORITY Admins
      Type: ImplicitMeta
    Readers:
      Rule: ANY Readers
      Type: ImplicitMeta
    Writers:
      Rule: ANY Writers
      Type: ImplicitMeta
Orderer:
  Addresses: &id006
  - ord1-hlf-ord.orderers.svc.cluster.local:7050
  - ord2-hlf-ord.orderers.svc.cluster.local:7050
  - ord3-hlf-ord.orderers.svc.cluster.local:7050
  BatchSize: &id007
    AbsoluteMaxBytes: 98MB
    MaxMessageCount: 100
    PreferredMaxBytes: 512KB
  BatchTimeout: 2s
  EtcdRaft: &id009
    Consenters:
    - ClientTLSCert: ./crypto-config/ordererOrganizations/orderers.svc.cluster.local/orderers/ord1-hlf-ord.orderers.svc.cluster.local/tls/server.crt
      Host: ord1-hlf-ord.orderers.svc.cluster.local
      Port: 7050
      ServerTLSCert: ./crypto-config/ordererOrganizations/orderers.svc.cluster.local/orderers/ord1-hlf-ord.orderers.svc.cluster.local/tls/server.crt
    - ClientTLSCert: ./crypto-config/ordererOrganizations/orderers.svc.cluster.local/orderers/ord2-hlf-ord.orderers.svc.cluster.local/tls/server.crt
      Host: ord2-hlf-ord.orderers.svc.cluster.local
      Port: 7050
      ServerTLSCert: ./crypto-config/ordererOrganizations/orderers.svc.cluster.local/orderers/ord2-hlf-ord.orderers.svc.cluster.local/tls/server.crt
    - ClientTLSCert: ./crypto-config/ordererOrganizations/orderers.svc.cluster.local/orderers/ord3-hlf-ord.orderers.svc.cluster.local/tls/server.crt
      Host: ord3-hlf-ord.orderers.svc.cluster.local
      Port: 7050
      ServerTLSCert: ./crypto-config/ordererOrganizations/orderers.svc.cluster.local/orderers/ord3-hlf-ord.orderers.svc.cluster.local/tls/server.crt
  OrdererType: etcdraft
  Organizations: &id010 {}
  Policies: &id011
    Admins:
      Rule: MAJORITY Admins
      Type: ImplicitMeta
    BlockValidation:
      Rule: ANY Writers
      Type: ImplicitMeta
    Readers:
      Rule: ANY Readers
      Type: ImplicitMeta
    Writers:
      Rule: ANY Writers
      Type: ImplicitMeta
Organizations:
- ID: OrdererMSP
  MSPDir: ./crypto-config/ordererOrganizations/orderers.svc.cluster.local/msp
  Name: OrdererOrg
  Policies:
    Admins:
      Rule: MAJORITY Admins
      Type: ImplicitMeta
    Readers:
      Rule: ANY Readers
      Type: ImplicitMeta
    Writers:
      Rule: ANY Writers
      Type: ImplicitMeta
- &id003
  AnchorPeers:
  - Host: peer1-hlf-peer.org1.svc.cluster.local
    Port: 7051
  ID: Org1MSP
  MSPDir: ./crypto-config/peerOrganizations/org1.svc.cluster.local/msp
  Name: Org1MSP
  Policies:
    Admins:
      Rule: MAJORITY Admins
      Type: ImplicitMeta
    Readers:
      Rule: ANY Readers
      Type: ImplicitMeta
    Writers:
      Rule: ANY Writers
      Type: ImplicitMeta
- &id004
  AnchorPeers:
  - Host: peer1-hlf-peer.org2.svc.cluster.local
    Port: 7051
  ID: Org2MSP
  MSPDir: ./crypto-config/peerOrganizations/org2.svc.cluster.local/msp
  Name: Org2MSP
  Policies:
    Admins:
      Rule: MAJORITY Admins
      Type: ImplicitMeta
    Readers:
      Rule: ANY Readers
      Type: ImplicitMeta
    Writers:
      Rule: ANY Writers
      Type: ImplicitMeta
- &id005
  AnchorPeers:
  - Host: peer1-hlf-peer.org3.svc.cluster.local
    Port: 7051
  ID: Org3MSP
  MSPDir: ./crypto-config/peerOrganizations/org3.svc.cluster.local/msp
  Name: Org3MSP
  Policies:
    Admins:
      Rule: MAJORITY Admins
      Type: ImplicitMeta
    Readers:
      Rule: ANY Readers
      Type: ImplicitMeta
    Writers:
      Rule: ANY Writers
      Type: ImplicitMeta
Profiles:
  OrdererGenesis:
    Capabilities: *id002
    Consortiums:
      MyConsortium:
        Organizations:
        - *id003
        - *id004
        - *id005
    Orderer:
      Addresses: *id006
      BatchSize: *id007
      BatchTimeout: 2s
      Capabilities: *id008
      EtcdRaft: *id009
      OrdererType: etcdraft
      Organizations: *id010
      Policies: *id011
    Policies: *id012
  TestChannel:
    Application:
      Capabilities: *id001
      Organizations:
      - *id003
      - *id004
      - *id005
      Policies: *id013
    Capabilities: *id002
    Consortium: MyConsortium
    Policies: *id012
