OrdererOrgs:

  - Name: OrdererOrg
    Domain: orderers.svc.cluster.local
    Specs:
      - Hostname: ord1-hlf-ord
      - Hostname: ord2-hlf-ord
      - Hostname: ord3-hlf-ord

PeerOrgs:

  - Name: Org1
    Domain: org1.svc.cluster.local
    Template:
      Count: 1
      Hostname: "peer1-hlf-peer"
    Users:
      Count: 1

  - Name: Org2
    Domain: org2.svc.cluster.local
    Template:
      Count: 1
      Hostname: "peer2-hlf-peer"
    Users:
      Count: 1

  - Name: Org3
    Domain: org3.svc.cluster.local
    Template:
      Count: 1
      Hostname: "peer3-hlf-peer"
    Users:
      Count: 1