apiVersion: v1
kind: Pod
metadata:
  name: fabric-tools
  namespace: fabric-tools
spec:
  containers:
    - name: fabrictools
      image: hyperledger/fabric-tools:amd64-1.3.0
      imagePullPolicy: IfNotPresent
      command: ["sh", "-c", "sleep 48h"]
      env:
      - name: TZ
        value: "Etc/UTC"
      - name: FABRIC_CFG_PATH
        value: "/fabric"
      - name: CORE_PEER_TLS_ENABLED
        value: "true"
      - name: CORE_PEER_TLS_CLIENTAUTHREQUIRED
        value: "true"
      - name:  CORE_PEER_TLS_CLIENTROOTCAS_FILES
        value: "/fabric/config/crypto/peerOrganizations/org1.svc.cluster.local/peers/peer1-hlf-peer.org1.svc.cluster.local/tls/ca.crt /fabric/config/crypto/peerOrganizations/org2.svc.cluster.local/peers/peer2-hlf-peer.org2.svc.cluster.local/tls/ca.crt /fabric/config/crypto/peerOrganizations/org3.svc.cluster.local/peers/peer3-hlf-peer.org3.svc.cluster.local/tls/ca.crt"
      - name: CORE_PEER_TLS_CLIENTCERT_FILE
        value: "/fabric/config/crypto/peerOrganizations/org1.svc.cluster.local/peers/peer1-hlf-peer.org1.svc.cluster.local/tls/tls.crt"
      - name: CORE_PEER_TLS_CLIENTKEY_FILE
        value: "/fabric/config/crypto/peerOrganizations/org1.svc.cluster.local/peers/peer1-hlf-peer.org1.svc.cluster.local/tls/tls.key"
      - name: CORE_PEER_TLS_CERT_FILE
        value: "/fabric/config/crypto/peerOrganizations/org1.svc.cluster.local/peers/peer1-hlf-peer.org1.svc.cluster.local/tls/tls.crt"
      - name: CORE_PEER_TLS_KEY_FILE
        value: "/fabric/config/crypto/peerOrganizations/org1.svc.cluster.local/peers/peer1-hlf-peer.org1.svc.cluster.local/tls/tls.key"
      - name: CORE_PEER_TLS_ROOTCERT_FILE
        value: "/fabric/config/crypto/peerOrganizations/org1.svc.cluster.local/peers/peer1-hlf-peer.org1.svc.cluster.local/tls/ca.crt"
      - name: CORE_PEER_MSPCONFIGPATH
        value: "/fabric/config/crypto/peerOrganizations/org1.svc.cluster.local/peers/peer1-hlf-peer.org1.svc.cluster.local/msp"
      - name: CORE_PEER_ID
        value: "cli"
      - name: CORE_PEER_ADDRESS
        value: "peer1-hlf-peer.org1.svc.cluster.local:7051"
      - name: CORE_PEER_LOCALMSPID
        value: "Org1MSP"
      volumeMounts:
        # MSP + TLS
        - mountPath: /fabric/config/crypto/
          name: crypto-config
        # Channel artifacts
        - mountPath: /fabric/config/channel-artifacts
          name: artifacts
        # Scripts (create channel, join peer, install & instantiate chaincode)
        - mountPath: /fabric/config/scripts
          name: scripts
        # Chaincode
        - mountPath: fabric/chaincode
          name: chaincode
        # Docker socket
        - mountPath: /host/var/run/docker.sock
          name: dockersocket
  volumes:
    - name: crypto-config
      hostPath:
        path: /hosthome/prehi/thesis/network/crypto-config/
    # Channel artifacts (genesis block, channel tx, anchor update txs)
    - name: artifacts
      secret:
        secretName: hlf--artifacts
    # Scripts
    - name: scripts
      secret:
        secretName: hlf--scripts
    # Chaincode
    - name: chaincode
      secret:
        secretName: hlf--chaincode
    # Docker socket
    - name: dockersocket
      hostPath:
        path: /var/run/docker.sock