apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ord2-hlf-ord
  namespace: orderers
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: ord2-hlf-ord
    spec:
      containers:

        - name: ord2-hlf-ord
          image: hyperledger/fabric-orderer:1.4.3
          imagePullPolicy: IfNotPresent
          command: ["sh", "-c", "orderer"]
          env:
          - name: TZ
            value: "Etc/UTC"
          - name: FABRIC_LOGGING_SPEC
            value: "info"
          - name: GODEBUG
            value: "netdns=go"
          - name: ORDERER_GENERAL_LISTENADDRESS
            value: "0.0.0.0"
          - name: ORDERER_GENERAL_GENESISMETHOD
            value: "file"
          - name: ORDERER_GENERAL_GENESISFILE
            value: "/etc/hyperledger/config/genesis.block"
          - name: ORDERER_GENERAL_TLS_ENABLED
            value: "true"
          - name: ORDERER_GENERAL_TLS_CERTIFICATE
            value: "/etc/hyperledger/msp/orderer/tls/server.crt"
          - name: ORDERER_GENERAL_TLS_PRIVATEKEY
            value: "/etc/hyperledger/msp/orderer/tls/server.key"
          - name: ORDERER_GENERAL_TLS_ROOTCAS
            value: "/etc/hyperledger/msp/orderer/tls/ca.crt"
          - name: ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE
            value: "/etc/hyperledger/msp/orderer/tls/server.crt"
          - name: ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY
            value: "/etc/hyperledger/msp/orderer/tls/server.key"
          - name: ORDERER_GENERAL_LOCALMSPDIR
            value: "/etc/hyperledger/msp/orderer/msp"
          - name: ORDERER_GENERAL_LOCALMSPID
            value: "OrdererMSP"
          volumeMounts:
            # MSP + TLS
            - mountPath: /etc/hyperledger/msp/orderer/
              name: crypto-config-2
            # Channel artifacts
            - mountPath: /etc/hyperledger/config/
              name: artifacts

      volumes:
        - name: crypto-config-2
          hostPath:
            path: /hosthome/prehi/thesis/network/crypto-config/ordererOrganizations/orderers.svc.cluster.local/orderers/ord2-hlf-ord.orderers.svc.cluster.local/
        # Channel artifacts (genesis block, channel tx, anchor update txs)
        - name: artifacts
          secret:
            secretName: hlf--artifacts