apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: peer1-hlf-peer
  namespace: org1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: peer1-hlf-peer
    spec:
      containers:
        - name: peer
          image: hyperledger/fabric-peer:1.4.3
          imagePullPolicy: IfNotPresent
          command: ["sh", "-c", "peer node start"]
          env:
          - name: TZ
            value: "Etc/UTC"
          - name: CORE_VM_ENDPOINT
            value: "unix:///host/var/run/docker.sock"
          - name: CORE_PEER_NETWORKID
            value: "nid1"
          - name: FABRIC_CFG_PATH
            value: "/etc/hyperledger/fabric/"
          - name: FABRIC_LOGGING_SPEC
            value: "INFO"
          - name: CORE_PEER_GOSSIP_USELEADERELECTION
            value: "true"
          - name: CORE_PEER_GOSSIP_ORGLEADER
            value: "false"
          - name: CORE_PEER_GOSSIP_BOOTSTRAP
            value: "localhost:7051"
          - name: CORE_PEER_GOSSIP_EXTERNALENDPOINT
            value: "minikube:30151"
          - name: CORE_PEER_ADDRESSAUTODETECT
            value: "true"
          - name: CORE_PEER_LISTENADDRESS
            value: "0.0.0.0:7051"
          - name: CORE_PEER_EVENTS_ADDRESS
            value: "0.0.0.0:7053"
          - name: CORE_PEER_PROFILE_ENABLED
            value: "true"
          - name: CORE_PEER_ID
            value: "peer1-hlf-peer.org1.svc.cluster.local"
          - name: CORE_PEER_TLS_ENABLED
            value: "true"
          - name: CORE_PEER_TLS_CERT_FILE
            value: "/fabric/config/crypto/peer/tls/tls.crt"
          - name: CORE_PEER_TLS_KEY_FILE
            value: "/fabric/config/crypto/peer/tls/tls.key"
          - name: CORE_PEER_TLS_ROOTCERT_FILE
            value: "/fabric/config/crypto/peer/tls/ca.crt"
          - name: CORE_PEER_MSPCONFIGPATH
            value: "/fabric/config/crypto/peer/msp"
          # - name: CORE_PEER_ADDRESS
          #   value: "peer1-hlf-peer.org1.svc.cluster.local:7051"
          - name: CORE_PEER_LOCALMSPID
            value: "Org1MSP"
          - name: CORE_LEDGER_STATE_STATEDATABASE
            value: "CouchDB"
          - name: CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS
            value: "localhost:5984"
          - name: CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME
            value: "hyperledgeruser"
          - name: CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
            value: "hyperledgerpass"
          volumeMounts:
            # Peer MSP + TLS
            - mountPath: /fabric/config/crypto/peer/
              name: crypto-config
            # Docker socket
            - mountPath: /host/var/run/docker.sock
              name: dockersocket
        - name: couchdb
          image: hyperledger/fabric-couchdb:amd64-0.4.14
          env:
          - name: TZ
            value: "Etc/UTC"
          - name: COUCHDB_USER
            value: "hyperledgeruser"
          - name: COUCHDB_PASSWORD
            value: "hyperledgerpass"
      volumes:
        # Peer MSP + TLS
        - name: crypto-config
          hostPath:
            path: /hosthome/prehi/thesis/network/crypto-config/peerOrganizations/org1.svc.cluster.local/peers/peer1-hlf-peer.org1.svc.cluster.local
        # Docker socket
        - name: dockersocket
          hostPath:
            path: /var/run/docker.sock