OrdererOrgs:
- Domain: orderers.svc.cluster.local
  Name: OrdererOrg
  Specs:
  - Hostname: ord1-hlf-ord
  - Hostname: ord2-hlf-ord
  - Hostname: ord3-hlf-ord
PeerOrgs:
- Domain: org1.svc.cluster.local
  Name: Org1
  Specs:
  - Hostname: peer1-hlf-peer
  - Hostname: peer2-hlf-peer
  - Hostname: peer3-hlf-peer
  - Hostname: peer4-hlf-peer
  Users:
    Count: 1
- Domain: org2.svc.cluster.local
  Name: Org2
  Specs:
  - Hostname: peer1-hlf-peer
  - Hostname: peer2-hlf-peer
  - Hostname: peer3-hlf-peer
  - Hostname: peer4-hlf-peer
  Users:
    Count: 1
- Domain: org3.svc.cluster.local
  Name: Org3
  Specs:
  - Hostname: peer1-hlf-peer
  - Hostname: peer2-hlf-peer
  - Hostname: peer3-hlf-peer
  - Hostname: peer4-hlf-peer
  Users:
    Count: 1
- Domain: org4.svc.cluster.local
  Name: Org4
  Specs:
  - Hostname: peer1-hlf-peer
  - Hostname: peer2-hlf-peer
  - Hostname: peer3-hlf-peer
  - Hostname: peer4-hlf-peer
  Users:
    Count: 1
- Domain: org5.svc.cluster.local
  Name: Org5
  Specs:
  - Hostname: peer1-hlf-peer
  - Hostname: peer2-hlf-peer
  - Hostname: peer3-hlf-peer
  - Hostname: peer4-hlf-peer
  Users:
    Count: 1
- Domain: org6.svc.cluster.local
  Name: Org6
  Specs:
  - Hostname: peer1-hlf-peer
  - Hostname: peer2-hlf-peer
  - Hostname: peer3-hlf-peer
  - Hostname: peer4-hlf-peer
  Users:
    Count: 1
- Domain: org7.svc.cluster.local
  Name: Org7
  Specs:
  - Hostname: peer1-hlf-peer
  - Hostname: peer2-hlf-peer
  - Hostname: peer3-hlf-peer
  - Hostname: peer4-hlf-peer
  Users:
    Count: 1
- Domain: org8.svc.cluster.local
  Name: Org8
  Specs:
  - Hostname: peer1-hlf-peer
  - Hostname: peer2-hlf-peer
  - Hostname: peer3-hlf-peer
  - Hostname: peer4-hlf-peer
  Users:
    Count: 1
