apiVersion: v1
kind: Service
metadata:
  name: ordORD_NUMBER-hlf-ord
  namespace: orderers
  labels:
    app: ordORD_NUMBER-hlf-ord
spec:
  type: ClusterIP
  selector:
    name: ordORD_NUMBER-hlf-ord
  ports:
  - protocol: TCP
    port: 7050
    name: grpcs
  - protocol: TCP
    port: 8443
    name: operations
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ordORD_NUMBER-service-monitor
  namespace: monitoring
  labels:
    app: ordORD_NUMBER-hlf-ord
    release: prometheus
spec:
  selector:
    matchLabels:
      app: ordORD_NUMBER-hlf-ord
  endpoints:
  - port: operations
    interval: 10s
