apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: PEER_NAME
  namespace: ORG_NAME
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: PEER_NAME
    spec:
      containers:
        - name: peer
          image: hyperledger/fabric-peer:1.4.3
          imagePullPolicy: IfNotPresent
          command: ["sh", "-c", "peer node start"]
          env:
          - name: TZ
            value: "Etc/UTC"
          - name: CORE_VM_ENDPOINT
            value: "unix:///host/var/run/docker.sock"
          - name: FABRIC_CFG_PATH
            value: "/etc/hyperledger/fabric/"
          - name: FABRIC_LOGGING_SPEC
            value: "info"
          - name: GODEBUG
            value: "netdns=go"
          - name: CORE_PEER_GOSSIP_USELEADERELECTION
            value: "true"
          - name: CORE_PEER_GOSSIP_ORGLEADER
            value: "false"
          - name: CORE_PEER_GOSSIP_BOOTSTRAP
            value: "PEER_NAME-hlf-peer.ORG_NAME.svc.cluster.local:7051"
          - name: CORE_PEER_GOSSIP_EXTERNALENDPOINT
            value: "PEER_NAME-hlf-peer.ORG_NAME.svc.cluster.local:7051"
          - name: CORE_PEER_ADDRESSAUTODETECT
            value: "true"
          - name: CORE_PEER_LISTENADDRESS
            value: "0.0.0.0:7051"
          - name: CORE_PEER_EVENTS_ADDRESS
            value: "0.0.0.0:7053"
          - name: CORE_PEER_PROFILE_ENABLED
            value: "true"
          - name: CORE_PEER_ID
            value: "PEER_NAME-hlf-peer.ORG_NAME.svc.cluster.local"
          - name: CORE_PEER_TLS_ENABLED
            value: "true"
          - name: CORE_PEER_TLS_CERT_FILE
            value: "/fabric/config/crypto/peer/tls/server.crt"
          - name: CORE_PEER_TLS_KEY_FILE
            value: "/fabric/config/crypto/peer/tls/server.key"
          - name: CORE_PEER_TLS_ROOTCERT_FILE
            value: "/fabric/config/crypto/peer/tls/ca.crt"
          - name: CORE_PEER_TLS_CLIENTAUTHREQUIRED
            value: "false"
          - name: CORE_PEER_TLS_CLIENTROOTCAS_FILES
            value: "/fabric/config/crypto/peer/tls/ca.crt"
          - name: CORE_PEER_TLS_CLIENTCERT_FILE
            value: "/fabric/config/crypto/peer/tls/server.crt"
          - name: CORE_PEER_TLS_CLIENTKEY_FILE
            value: "/fabric/config/crypto/peer/tls/server.key"
          - name: CORE_PEER_MSPCONFIGPATH
            value: "/fabric/config/crypto/peer/msp"
          - name: CORE_PEER_LOCALMSPID
            value: "MSP_NAME"
          - name: CORE_METRICS_PROVIDER
            value: "prometheus"
          - name: CORE_OPERATIONS_LISTENADDRESS
            value: "0.0.0.0:9443"
          - name: CORE_LEDGER_STATE_STATEDATABASE
            value: "CouchDB"
          - name: CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS
            value: "localhost:5984"
          - name: CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME
            value: "hyperledgeruser"
          - name: CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
            value: "hyperledgerpass"
          volumeMounts:
            # Peer MSP + TLS
            - mountPath: /fabric/config/crypto/peer/
              name: crypto-config
            # Docker socket
            - mountPath: /host/var/run/docker.sock
              name: dockersocket
          ports:
            - name: request
              containerPort: 7051
              protocol: TCP
            - name: event
              containerPort: 7053
              protocol: TCP
            - name: operations
              containerPort: 9443
              protocol: TCP
        - name: couchdb
          image: hyperledger/fabric-couchdb:amd64-0.4.16
          env:
          - name: TZ
            value: "Etc/UTC"
          - name: COUCHDB_USER
            value: "hyperledgeruser"
          - name: COUCHDB_PASSWORD
            value: "hyperledgerpass"
          ports:
            - name: couchdb
              containerPort: 5984
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 5984
            initialDelaySeconds: 60
            timeoutSeconds: 5
            failureThreshold: 6
          readinessProbe:
            tcpSocket:
              port: 5984
            initialDelaySeconds: 5
            timeoutSeconds: 3
            periodSeconds: 5
      volumes:
        # Peer MSP + TLS
        - name: crypto-config
          hostPath:
            path: ABSPATH/network/crypto-config/peerOrganizations/ORG_NAME.svc.cluster.local/peers/PEER_NAME-hlf-peer.ORG_NAME.svc.cluster.local
            type: Directory
        # Docker socket
        - name: dockersocket
          hostPath:
            path: /var/run/docker.sock