apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: PEER_NAME-hlf-peer
    release: PEER_NAME
  name: PEER_NAME-expose
  namespace: ORG_NAME
spec:
  ports:
  - name: port-1
    port: PEER_REQ_PORT
    protocol: TCP
    targetPort: PEER_REQ_PORT
    nodePort: PEER_REQ_PORT
  - name: port-2
    port: PEER_EVENT_PORT
    protocol: TCP
    targetPort: PEER_EVENT_PORT
    nodePort: PEER_EVENT_PORT
  selector:
    app: hlf-peer
    release: PEER_NAME
  type: NodePort
status:
  loadBalancer: {}
