apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    release: PEER_NAME
  name: PEER_NAME-expose
  namespace: ORG_NAME
spec:
  ports:
  - name: port-1
    port: 7051
    protocol: TCP
    targetPort: 7051
    nodePort: PEER_REQ_PORT
  - name: port-2
    port: 7053
    protocol: TCP
    targetPort: 7053
    nodePort: PEER_EVENT_PORT
  selector:
    name: PEER_NAME-hlf-peer
  type: NodePort
status:
  loadBalancer: {}
