apiVersion: v1
kind: Service
metadata:
  name: PEER_NAME-hlf-peer
  namespace: ORG_NAME
  labels:
    app: PEER_NAME-hlf-peer
spec:
  type: ClusterIP 
  selector:
    name: PEER_NAME
  ports:
  - protocol: TCP
    port: 7051
    name: grpcs
  - protocol: TCP
    port: 7053
    name: events
  - protocol: TCP
    port: 5984
    name: couchdb
  - protocol: TCP
    port: 9443
    name: operations
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: PEER_NAME-service-monitor
  namespace: ORG_NAME
  labels:
    app: PEER_NAME-hlf-peer
    release: prometheus
spec:
  selector:
    matchLabels:
      app: PEER_NAME-hlf-peer # target gitlab service
  endpoints:
  - port: operations
    interval: 10s