apiVersion: v1
kind: Service
metadata:
  name: PEER_NAME-hlf-peer
  namespace: ORG_NAME
  labels:
    run: PEER_NAME-hlf-peer
spec:
  type: ClusterIP 
  selector:
    name: PEER_NAME
  ports:
  - protocol: TCP
    port: PEER_REQ_PORT
    name: grpcs
  - protocol: TCP
    port: PEER_EVENT_PORT
    name: events
  - protocol: TCP
    port: 5984
    name: couchdb