image:
  tag: 1.3.0

persistence:
  accessMode: ReadWriteOnce
  size: 1Gi

peer:
  databaseType: CouchDB
  couchdbInstance: cdb-peer0-org3
  mspID: Org3MSP

secrets:
  peer:
    cert: peer0org3-idcert
    key: peer0org3-idkey
    caCert: org3-cacert
  channel: channel
  adminCert: org3-admincert
  adminKey: org3-adminkey
  #caServerTls: ca--tls