prometheus:
  prometheusSpec:
    ruleNamespaceSelector: {}
    ruleSelector: {}
    podMonitorNamespaceSelector: {}
    podMonitorSelector: {}
    serviceMonitorNamespaceSelector: {}
    serviceMonitorSelector: {}
  service:
    type: NodePort
